Repository hyperledger/cello, pull requests merged in 2019-10, with the labels that each got.

#28 Removed the read only header in the doc
  README.md
Labels: enhancement

#27 Fix the image path
  README.md
Labels: bug

#29 [CE-713] Fabric Operator zip structure README
  docs/agents/fabric-operator.md
  src/agent/fabric-operator/README.md
  src/agent/fabric-operator/agent/config.yaml
Labels: documentation

#34 [Close #32] Add bug issue & pull request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Documentation

#38 [Close #37] Move make check into template
  azure-pipelines.yml
  ci/check.yml
Labels: Integration&Testing

#40 [Fix #39] Add curl install for ansible agent
  build_image/dockerhub/latest/agent/ansible/Dockerfile
Labels: bug

#41 In product mode, api engine docs can not find static files
  build_image/docker/common/nginx/nginx.conf.default
Labels: bug

#48 [Fix #47] Fix node status check crash for k8s agent
  src/agent/kubernetes-agent/src/operations/create_node.py
Labels: bug

#43 [Fix #42] Fix nginx server media url not working
  bootup/docker-compose-files/docker-compose.yml
  build_image/docker/common/nginx/nginx.conf.default
Labels: bug

#51 [Fix #50] Add api engine service port into dashboard
  bootup/docker-compose-files/docker-compose-dev.yml
  bootup/docker-compose-files/docker-compose.yml
  build_image/docker/common/dashboard/config-nginx.sh
  build_image/docker/common/dashboard/default.conf.tmpl
Labels: bug

#55 [Close #53] Refine bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Documentation, Integration&Testing

#56 [CE-716]Fixed the role binding issue
  src/agent/fabric-operator/README.md
  src/agent/fabric-operator/deploy/fabric-operator.yaml
  src/agent/fabric-operator/deploy/operator.yaml
  src/agent/fabric-operator/deploy/role.yaml
  src/agent/fabric-operator/deploy/role_binding.yaml
  src/agent/fabric-operator/deploy/service_account.yaml
Labels: bug

#57 [Fix #52] Fix k8s 1.16 later version not support.
  src/agent/kubernetes-agent/src/utils/client.py
  src/api-engine/requirements.txt
Labels: bug
